#pragma once

#include <vector>
#include <glim/preprocess/preprocessed_frame.hpp>
#include <gtsam_points/types/gaussian_voxelmap.hpp>
#include <glim/dynamic_rejection/dynamic_voxelmap_cpu.hpp>
#include <glim/common/cloud_covariance_estimation.hpp>



namespace glim {
struct DynamicObjectRejectionParamsCPU {
    public: 
        DynamicObjectRejectionParamsCPU();
        ~DynamicObjectRejectionParamsCPU();
    
    public:
        double mean_difference_threshold; ///< Threshold for mean difference to classify a point as dynamic
        double covariance_error_threshold; ///< Threshold for variance difference to classify a point as dynamic
        int points_number_difference_threshold; ///< Threshold for the number of points difference to classify a point as dynamic
        double mahalanobis_distance_threshold; ///< Threshold for Mahalanobis distance to classify a point as dynamic
        double dynamic_score_threshold; ///< Threshold for the combined dynamic score to classify a point as dynamic
        double voxel_resolution; 
        int voxelmap_levels;
        double voxelmap_scaling_factor;
        int num_threads;
        double w_shift;
        double w_mahalanobis;
        double w_covariance_difference;
        double w_shape;
        double w_occupancy;
        double history_factor;
        int frame_num_memory;

};


class DynamicObjectRejectionCPU {
public:

    /**
     * @brief Constructor
     */
  DynamicObjectRejectionCPU(const DynamicObjectRejectionParamsCPU& params = DynamicObjectRejectionParamsCPU());


    /**
      * @brief Get the indices of points classified as dynamic
      * @return std::vector<int> Indices of dynamic points
      */
  PreprocessedFrame::Ptr dynamic_object_rejection(const PreprocessedFrame::Ptr frame);
    /**
     * @brief Get the indices of points classified as dynamic
     * @return std::vector<int> Indices of dynamic points
     */
  std::vector<int> get_dynamic_points_indices() const { return dynamic_voxels_indices; }

  /**
   * @brief Get the last dynamic frame (points classified as dynamic)
   * @return PreprocessedFrame containing only dynamic points, or nullptr if none
   */
  PreprocessedFrame::Ptr get_last_dynamic_frame() const { return last_dynamic_frame; }
private:

  // Add odometry information to the voxelmaps (e.g., by transforming them according to the estimated pose) and return the updated voxelmaps
  std::vector<gtsam_points::DynamicVoxelMapCPU::Ptr> add_odometry(const std::vector<gtsam_points::DynamicVoxelMapCPU::Ptr>& voxelmaps, const Eigen::Isometry3d& T_world_imu);

  std::vector<int> find_neighbors(const Eigen::Vector4d* points, const int num_points, const int k) const;

  /**
     * @brief Recognize dynamic objects in the current frame by comparing it with the previous frame and return a new estimation frame without points classified as dynamic.
     * @param frame Current preprocessed frame
     * @param prev_frame Previous estimation frame
     * @return gtsam_points::DynamicVoxelMapCPU::Ptr New dynamic voxel map
    */
  gtsam_points::DynamicVoxelMapCPU::Ptr dynamic_object_recognition(gtsam_points::DynamicVoxelMapCPU::Ptr current_voxelmap, gtsam_points::DynamicVoxelMapCPU::Ptr prev_voxelmap);
private:
    DynamicObjectRejectionParamsCPU params_;
    std::vector<gtsam_points::DynamicVoxelMapCPU::Ptr> last_voxelmaps;  ///< most recent voxelmap generated by voxelize

    std::vector<int> dynamic_voxels_indices;

    std::vector<Eigen::Vector4d> static_points;
    std::vector<double> static_intensities;
    std::vector<double> static_times;

    std::vector<Eigen::Vector4d> dynamic_points;
    std::vector<double> dynamic_intensities;
    std::vector<double> dynamic_times;

    PreprocessedFrame::Ptr last_dynamic_frame;  ///< Last frame of dynamic-only points

    int recursive_level; // to keep track of the current level of recursion in the voxelmap hierarchy 
    std::unique_ptr<CloudCovarianceEstimation> covariance_estimation;

};

}  // namespace glim
